/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentMyDiscussionsRouteImport } from './routes/student/my-discussions'
import { Route as StudentMyCommunitiesRouteImport } from './routes/student/my-communities'
import { Route as StudentBrowseCommunitiesRouteImport } from './routes/student/browse-communities'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminDiscussionsRouteImport } from './routes/admin/discussions'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCommunitiesRouteImport } from './routes/admin/communities'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMyDiscussionsRoute = StudentMyDiscussionsRouteImport.update({
  id: '/my-discussions',
  path: '/my-discussions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMyCommunitiesRoute = StudentMyCommunitiesRouteImport.update({
  id: '/my-communities',
  path: '/my-communities',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBrowseCommunitiesRoute =
  StudentBrowseCommunitiesRouteImport.update({
    id: '/browse-communities',
    path: '/browse-communities',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscussionsRoute = AdminDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/discussions': typeof DiscussionsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discussions': typeof AdminDiscussionsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/student/browse-communities': typeof StudentBrowseCommunitiesRoute
  '/student/my-communities': typeof StudentMyCommunitiesRoute
  '/student/my-discussions': typeof StudentMyDiscussionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/discussions': typeof DiscussionsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discussions': typeof AdminDiscussionsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/student/browse-communities': typeof StudentBrowseCommunitiesRoute
  '/student/my-communities': typeof StudentMyCommunitiesRoute
  '/student/my-discussions': typeof StudentMyDiscussionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/discussions': typeof DiscussionsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discussions': typeof AdminDiscussionsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/student/browse-communities': typeof StudentBrowseCommunitiesRoute
  '/student/my-communities': typeof StudentMyCommunitiesRoute
  '/student/my-discussions': typeof StudentMyDiscussionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/communities'
    | '/discussions'
    | '/login'
    | '/register'
    | '/signup'
    | '/student'
    | '/admin/communities'
    | '/admin/dashboard'
    | '/admin/discussions'
    | '/admin/moderation'
    | '/student/browse-communities'
    | '/student/my-communities'
    | '/student/my-discussions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/communities'
    | '/discussions'
    | '/login'
    | '/register'
    | '/signup'
    | '/student'
    | '/admin/communities'
    | '/admin/dashboard'
    | '/admin/discussions'
    | '/admin/moderation'
    | '/student/browse-communities'
    | '/student/my-communities'
    | '/student/my-discussions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/communities'
    | '/discussions'
    | '/login'
    | '/register'
    | '/signup'
    | '/student'
    | '/admin/communities'
    | '/admin/dashboard'
    | '/admin/discussions'
    | '/admin/moderation'
    | '/student/browse-communities'
    | '/student/my-communities'
    | '/student/my-discussions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRoute
  DiscussionsRoute: typeof DiscussionsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/my-discussions': {
      id: '/student/my-discussions'
      path: '/my-discussions'
      fullPath: '/student/my-discussions'
      preLoaderRoute: typeof StudentMyDiscussionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/my-communities': {
      id: '/student/my-communities'
      path: '/my-communities'
      fullPath: '/student/my-communities'
      preLoaderRoute: typeof StudentMyCommunitiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/browse-communities': {
      id: '/student/browse-communities'
      path: '/browse-communities'
      fullPath: '/student/browse-communities'
      preLoaderRoute: typeof StudentBrowseCommunitiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discussions': {
      id: '/admin/discussions'
      path: '/discussions'
      fullPath: '/admin/discussions'
      preLoaderRoute: typeof AdminDiscussionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiscussionsRoute: typeof AdminDiscussionsRoute
  AdminModerationRoute: typeof AdminModerationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiscussionsRoute: AdminDiscussionsRoute,
  AdminModerationRoute: AdminModerationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentBrowseCommunitiesRoute: typeof StudentBrowseCommunitiesRoute
  StudentMyCommunitiesRoute: typeof StudentMyCommunitiesRoute
  StudentMyDiscussionsRoute: typeof StudentMyDiscussionsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBrowseCommunitiesRoute: StudentBrowseCommunitiesRoute,
  StudentMyCommunitiesRoute: StudentMyCommunitiesRoute,
  StudentMyDiscussionsRoute: StudentMyDiscussionsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunitiesRoute: CommunitiesRoute,
  DiscussionsRoute: DiscussionsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
